# 09b — Mode-B Shortcut Audit

**Highest-priority task before any further ranker training.** Audits whether notebook 09's
suspicious `mode_b_unseen_connectivity_mrr25 ~= 0.4999` reflects genuine unseen-structure
spectral generalization, or a leakage shortcut baked into how the unseen-connectivity candidate
pool is currently built.

Hypothesis (`casmi.ranking.audit` module docstring, `casmi.spectra.library` module docstring):
under unseen-connectivity CV, the TRUE candidate structurally has every spectral feature NaN --
its own connectivity's reference spectra are, by construction, all in the held-out fold. If a
large share of FALSE candidates share that exact all-NaN pattern, "all spectral features
missing" can act as a fold-membership fingerprint LightGBM's native missing-value branching can
exploit, even though `casmi.ranking.feature_policy` already excludes `has_reference_spectrum`/
`n_reference_spectra` as raw features -- that governance blocks explicit columns, not a model
branching on the MISSINGNESS of columns it IS allowed to see.

This notebook does not retrain a production model. It reproduces notebook 09's exact fold
models (same features, params, seed, folds) purely as the audit subject, then runs every control
from `casmi.ranking.audit` against them. Every number below is computed live against the real
dev data -- nothing hand-typed.

In [1]:
import sys, json, time
from pathlib import Path

NOTEBOOK_START_TIME = time.time()

REPO_ROOT = Path.cwd()
if not (REPO_ROOT / "src").exists() and (REPO_ROOT.parent / "src").exists():
    REPO_ROOT = REPO_ROOT.parent
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

import numpy as np
import pandas as pd
import lightgbm as lgb

from casmi.paths import get_project_paths
from casmi.ranking.evaluation import rank_candidates, ranking_metrics, true_candidate_rank, per_query_reciprocal_rank
from casmi.ranking.feature_policy import SPECTRAL_RANKING_FEATURE_POLICY, assert_no_prohibited_features
from casmi.ranking import audit as mode_b_audit
from casmi.validation.checks import CheckResult, summarize_checks
from casmi.validation.baseline_registry import load_baseline, load_promoted_baseline, register_baseline, list_baselines
from casmi.validation.bootstrap import paired_bootstrap_report

pd.set_option("display.max_columns", 60)
pd.set_option("display.width", 160)

SEED = 42
N_BOOTSTRAP = 5000
# IDENTICAL to notebook 09 -- this audit's subject must be the SAME trained model notebook 09
# reported 0.4999 for, not a re-tuned one.
LGBM_PARAMS = dict(
    objective="lambdarank", metric="ndcg", n_estimators=300, learning_rate=0.05,
    num_leaves=31, min_child_samples=20, random_state=SEED, verbosity=-1,
)

paths = get_project_paths()
CG_INTERIM = paths.interim / "candidate_generation"
CG_PROCESSED = paths.processed / "candidate_generation"
RANK_INTERIM = paths.interim / "spectral_ranking"
AUDIT_PROCESSED = paths.processed / "mode_b_audit"
AUDIT_PROCESSED.mkdir(parents=True, exist_ok=True)
BASELINE_REGISTRY_PATH = paths.processed / "baseline_registry.json"
REPORTS_DIR = paths.reports
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

MODEL_FEATURES = SPECTRAL_RANKING_FEATURE_POLICY.model_features
checks = []
print(f"MODEL_FEATURES ({len(MODEL_FEATURES)}): {MODEL_FEATURES}")
print(f"SPECTRAL_FEATURES ({len(mode_b_audit.SPECTRAL_FEATURES)}): {mode_b_audit.SPECTRAL_FEATURES}")

MODEL_FEATURES (9): ['abs_mass_error_ppm', 'cosine_max', 'cosine_top3_mean', 'modified_cosine_max', 'modified_cosine_top3_mean', 'peak_overlap_frac_max', 'peak_overlap_frac_top3_mean', 'neutral_loss_cosine_max', 'neutral_loss_cosine_top3_mean']
SPECTRAL_FEATURES (8): ['cosine_max', 'cosine_top3_mean', 'modified_cosine_max', 'modified_cosine_top3_mean', 'peak_overlap_frac_max', 'peak_overlap_frac_top3_mean', 'neutral_loss_cosine_max', 'neutral_loss_cosine_top3_mean']

## 1. Reload notebook 03/04 artifacts and reproduce notebook 09's exact fold models

No new spectral computation -- same `pair_features_dev_known_spectrum.parquet` / `pair_features_dev_unseen_connectivity.parquet` notebook 09 used, same 5 connectivity-safe folds, same `LGBM_PARAMS`/`SEED`. Reproducing (not loading -- notebook 09 never persisted its fold models to disk) lets this audit interrogate the ACTUAL model notebook 09 scored, confirmed by matching its registered MRR numbers before trusting anything downstream.

In [2]:
notebook_09_baseline = load_baseline("notebook_09_lambdamart", BASELINE_REGISTRY_PATH)
assert notebook_09_baseline is not None, "notebook 09 must be run first -- its baseline_registry entry is required here"

# notebook 09 registers a NESTED, status-carrying schema (mode_a/mode_b dicts, each with its own
# status) -- this audit is explicitly the thing ALLOWED to read the invalidated mode_b number
# (that's its whole job), so it reads it directly with allow_invalid=True rather than being
# blocked by load_promoted_baseline like every other consumer should be.
mode_a_mrr25_registered = load_promoted_baseline("notebook_09_lambdamart", BASELINE_REGISTRY_PATH, regime="mode_a")["mrr_at_25"]
mode_b_mrr25_registered = load_promoted_baseline("notebook_09_lambdamart", BASELINE_REGISTRY_PATH, regime="mode_b", allow_invalid=True)["mrr_at_25"]
print(f"registered (notebook 09, via load_promoted_baseline): mode_a={mode_a_mrr25_registered:.4f} (promoted), mode_b={mode_b_mrr25_registered:.4f} (allow_invalid=True)")

dev_ranking_queries = pd.read_parquet(RANK_INTERIM / "dev_ranking_queries.parquet")
pair_features_dev_known = pd.read_parquet(RANK_INTERIM / "pair_features_dev_known_spectrum.parquet")
pair_features_dev_unseen = pd.read_parquet(RANK_INTERIM / "pair_features_dev_unseen_connectivity.parquet")

all_dev_query_ids = dev_ranking_queries["query_id"].tolist()
train_table = pair_features_dev_known.merge(dev_ranking_queries[["query_id", "fold", "true_connectivity_key"]], on="query_id", how="left")
assert train_table["fold"].notna().all()
assert_no_prohibited_features(train_table[MODEL_FEATURES], SPECTRAL_RANKING_FEATURE_POLICY)

unseen_table = pair_features_dev_unseen.merge(dev_ranking_queries[["query_id", "fold"]], on="query_id", how="left")
assert unseen_table["fold"].notna().all()

print(f"train_table (known-spectrum / Mode A): {train_table.shape}")
print(f"unseen_table (unseen-connectivity / Mode B): {unseen_table.shape}")
checks.append(CheckResult("upstream artifacts loaded", True, "notebook 03/04/09 artifacts reloaded, no recomputation"))

registered (notebook 09, via load_promoted_baseline): mode_a=0.7531 (promoted), mode_b=0.4999 (allow_invalid=True)

train_table (known-spectrum / Mode A): (248027, 16)
unseen_table (unseen-connectivity / Mode B): (248027, 15)

In [3]:
oof_scores = pd.Series(np.nan, index=train_table.index)
fold_models = {}

for held_out_fold in sorted(train_table["fold"].unique()):
    tr = train_table[train_table["fold"] != held_out_fold].sort_values("query_id")
    va = train_table[train_table["fold"] == held_out_fold].sort_values("query_id")
    tr_group = tr.groupby("query_id", sort=True).size().to_numpy()
    model = lgb.LGBMRanker(**LGBM_PARAMS)
    model.fit(tr[MODEL_FEATURES], tr["is_true_candidate"].astype(int), group=tr_group)
    oof_scores.loc[va.index] = model.predict(va[MODEL_FEATURES])
    fold_models[held_out_fold] = model

train_table = train_table.assign(lambdamart_score=oof_scores)
lmart_ranked = rank_candidates(train_table.assign(score=train_table["lambdamart_score"]), score_col="score", ascending=False)
lmart_metrics = ranking_metrics(lmart_ranked, all_dev_query_ids, k_values=(1, 5, 10, 25))

oof_scores_unseen = pd.Series(np.nan, index=unseen_table.index)
for held_out_fold, model in fold_models.items():
    mask = unseen_table["fold"] == held_out_fold
    oof_scores_unseen.loc[mask] = model.predict(unseen_table.loc[mask, MODEL_FEATURES])
unseen_table = unseen_table.assign(lambdamart_score=oof_scores_unseen)
lmart_unseen_ranked = rank_candidates(unseen_table.assign(score=unseen_table["lambdamart_score"]), score_col="score", ascending=False)
lmart_unseen_metrics = ranking_metrics(lmart_unseen_ranked, all_dev_query_ids, k_values=(1, 5, 10, 25))

reproduced = {
    "mode_a_known_spectrum_mrr25": lmart_metrics["end_to_end"]["mrr_at_25"],
    "mode_b_unseen_connectivity_mrr25": lmart_unseen_metrics["end_to_end"]["mrr_at_25"],
}
print("reproduced:", reproduced)
print("registered (notebook 09):", {"mode_a_known_spectrum_mrr25": mode_a_mrr25_registered, "mode_b_unseen_connectivity_mrr25": mode_b_mrr25_registered})

reproduction_matches = (
    abs(reproduced["mode_a_known_spectrum_mrr25"] - mode_a_mrr25_registered) < 1e-6
    and abs(reproduced["mode_b_unseen_connectivity_mrr25"] - mode_b_mrr25_registered) < 1e-6
)
print(f"\nexact reproduction of notebook 09's registered numbers: {'PASS' if reproduction_matches else 'FAIL (see note below)'}")
checks.append(CheckResult("reproduced fold models match notebook 09's registered Mode A/B MRR", reproduction_matches,
                           f"reproduced={reproduced}, registered mode_a={mode_a_mrr25_registered}, mode_b={mode_b_mrr25_registered}"))

reproduced: {'mode_a_known_spectrum_mrr25': 0.7531158417438442, 'mode_b_unseen_connectivity_mrr25': 0.49990025158323076}
registered (notebook 09): {'mode_a_known_spectrum_mrr25': 0.7531158417438442, 'mode_b_unseen_connectivity_mrr25': 0.49990025158323076}

exact reproduction of notebook 09's registered numbers: PASS

## 2. Section 1.3 -- explicit missingness table

`casmi.ranking.audit.summarize_feature_missingness` on the Mode-B (unseen-connectivity) pair table: does "all spectral features missing" separate true from false candidates, and does the false-candidate rate match a fold-size fraction (5 folds -> 1/5 = 0.20)?

In [4]:
unseen_augmented, missingness_summary = mode_b_audit.summarize_feature_missingness(
    unseen_table, n_folds=dev_ranking_queries["fold"].nunique(), fold_tolerance=0.05,
)
missingness_summary_df = pd.DataFrame([missingness_summary])
display(missingness_summary_df.T.rename(columns={0: "value"}))

print(f"\nP(all spectral NaN | true)  = {missingness_summary['p_all_nan_given_true']:.4f}")
print(f"P(all spectral NaN | false) = {missingness_summary['p_all_nan_given_false']:.4f}")
print(f"per-query all-NaN fraction: median={missingness_summary['per_query_all_nan_fraction_median']:.4f}, "
      f"p25={missingness_summary['per_query_all_nan_fraction_p25']:.4f}, "
      f"p75={missingness_summary['per_query_all_nan_fraction_p75']:.4f}, "
      f"p90={missingness_summary['per_query_all_nan_fraction_p90']:.4f}")
print(f"expected 1/n_folds = {missingness_summary['expected_fold_fraction']:.4f}")
if missingness_summary["fold_membership_shortcut_flag"]:
    print("\n*** POSSIBLE FOLD-MEMBERSHIP SHORTCUT: median per-query all-NaN fraction matches 1/n_folds ***")
checks.append(CheckResult("missingness table computed on real Mode-B pair table", True,
                           f"n_rows={missingness_summary['n_rows']}, n_queries={missingness_summary['n_queries']}"))

                                      value
n_rows                               248027
n_queries                               996
p_all_nan_given_true                    1.0
p_all_nan_given_false              0.198691
p_any_nan_given_true                    1.0
p_any_nan_given_false              0.198691
per_query_all_nan_fraction_median  0.207633
per_query_all_nan_fraction_p25     0.184705
per_query_all_nan_fraction_p75     0.237256
per_query_all_nan_fraction_p90     0.333333
expected_fold_fraction                  0.2
fold_membership_shortcut_flag          True

P(all spectral NaN | true)  = 1.0000
P(all spectral NaN | false) = 0.1987
per-query all-NaN fraction: median=0.2076, p25=0.1847, p75=0.2373, p90=0.3333
expected 1/n_folds = 0.2000

*** POSSIBLE FOLD-MEMBERSHIP SHORTCUT: median per-query all-NaN fraction matches 1/n_folds ***

## 3. Section 1.4 -- mass-only ranking WITHIN the all-spectral-NaN subset

Restrict candidates to `all_spectral_nan == True` (the subset the true candidate always falls into) and rank by mass alone. How much of the suspicious 0.4999 does this explain?

In [5]:
missing_subset_mass_only = mode_b_audit.evaluate_missingness_shortcut(unseen_augmented, all_query_ids=all_dev_query_ids)
print(f"mass-only MRR@25 WITHIN all-spectral-NaN subset (end-to-end, {missing_subset_mass_only['n_queries_total']} queries): "
      f"{missing_subset_mass_only['end_to_end']['mrr_at_25']:.4f}")
print(f"  vs. full-pool classical mass-only (registered, notebook 04): {load_baseline('notebook_04_classical_baselines', BASELINE_REGISTRY_PATH)['known_spectrum']['mass_only']:.4f}")
print(f"  vs. suspicious Mode-B LambdaMART MRR@25 (registered, notebook 09): {mode_b_mrr25_registered:.4f}")

fraction_explained_by_missing_subset_mass_only = (
    missing_subset_mass_only["end_to_end"]["mrr_at_25"] / mode_b_mrr25_registered
)
print(f"\nfraction of Mode-B MRR explained by mass-only-within-missing-subset: {fraction_explained_by_missing_subset_mass_only:.1%}")
checks.append(CheckResult("mass-only-within-all-NaN-subset MRR computed", True,
                           f"MRR@25={missing_subset_mass_only['end_to_end']['mrr_at_25']:.4f}"))

mass-only MRR@25 WITHIN all-spectral-NaN subset (end-to-end, 1000 queries): 0.5218
  vs. full-pool classical mass-only (registered, notebook 04): 0.2899
  vs. suspicious Mode-B LambdaMART MRR@25 (registered, notebook 09): 0.4999

fraction of Mode-B MRR explained by mass-only-within-missing-subset: 104.4%

## 4. Section 1.5 -- constant-spectral-feature control

Replace every spectral feature, for every Mode-B candidate, with the SAME finite constant (`0.0`, never NaN) and rescore with the SAME trained fold models. If performance collapses close to the mass-only baseline, the real-feature Mode-B score was substantially driven by spectral-value/missingness STRUCTURE rather than genuine spectral discrimination.

In [6]:
constant_control = mode_b_audit.constant_spectral_feature_control(
    fold_models, unseen_table, model_features=MODEL_FEATURES, spectral_features=mode_b_audit.SPECTRAL_FEATURES,
    constant_value=0.0, fold_col="fold", all_query_ids=all_dev_query_ids,
)
assert abs(constant_control["real_features_mrr_at_25"] - mode_b_mrr25_registered) < 1e-9, (
    "real-feature control MRR must exactly match the registered Mode-B MRR -- same scores, same denominator"
)
mass_only_mrr = load_baseline("notebook_04_classical_baselines", BASELINE_REGISTRY_PATH)["known_spectrum"]["mass_only"]

control_comparison = pd.DataFrame([
    {"scenario": "real spectral features (Mode-B LambdaMART, as registered)", "mrr_at_25": constant_control["real_features_mrr_at_25"]},
    {"scenario": "constant spectral features (all candidates, value=0.0)", "mrr_at_25": constant_control["constant_spectral_features_mrr_at_25"]},
    {"scenario": "classical mass-only (known-spectrum, registered)", "mrr_at_25": mass_only_mrr},
])
display(control_comparison)
print(f"\nreal - constant = {constant_control['difference']:+.4f}")
print(f"constant - mass_only = {constant_control['constant_spectral_features_mrr_at_25'] - mass_only_mrr:+.4f}")
checks.append(CheckResult("constant-spectral-feature control computed", True, str(control_comparison.to_dict("records"))))

                                            scenario  mrr_at_25
0  real spectral features (Mode-B LambdaMART, as ...   0.499900
1  constant spectral features (all candidates, va...   0.253191
2   classical mass-only (known-spectrum, registered)   0.289946

real - constant = +0.2467
constant - mass_only = -0.0368

## 5. Section 1.6 -- missingness-only diagnostic model

An intentionally crippled leave-one-fold-out ranker trained on ONLY `abs_mass_error_ppm` + `spectral_missing_count` + `all_spectral_nan` -- explicitly no real spectral-similarity values. Same connectivity-safe folds. If it recovers a large share of the full Mode-B LambdaMART's MRR, that "skill" is mostly the missingness pattern, not spectral discrimination.

In [7]:
missingness_only_result = mode_b_audit.missingness_only_baseline(unseen_table, lgbm_params=LGBM_PARAMS, seed=SEED, all_query_ids=all_dev_query_ids)
print(f"features used: {missingness_only_result['features_used']}")
print(f"missingness-only MRR@25: {missingness_only_result['mrr_at_25']:.4f}")

fraction_of_full_model_recovered = missingness_only_result["mrr_at_25"] / mode_b_mrr25_registered
print(f"\nfraction of the full Mode-B LambdaMART's MRR recovered by missingness-only features: {fraction_of_full_model_recovered:.1%}")
checks.append(CheckResult("missingness-only diagnostic model trained and evaluated OOF", True,
                           f"MRR@25={missingness_only_result['mrr_at_25']:.4f}"))

features used: ['abs_mass_error_ppm', 'spectral_missing_count', 'all_spectral_nan']
missingness-only MRR@25: 0.5036

fraction of the full Mode-B LambdaMART's MRR recovered by missingness-only features: 100.7%

## 6. Shortcut-detection controls applied directly to the Mode-B-scoring model

`candidate_order_control` / `spectrum_mask_control` (section 13.2-13.3), run on the actual unseen-connectivity table and fold-0 model -- confirms the audited model is order-invariant and genuinely spectrum-sensitive, so the missingness finding above isn't confounded by some other bug.

In [8]:
fold0 = sorted(unseen_table["fold"].unique())[0]
model0 = fold_models[fold0]
val0 = unseen_table[unseen_table["fold"] == fold0].sort_values("query_id")

order_result = mode_b_audit.candidate_order_control(model0, val0, model_features=MODEL_FEATURES)
print(f"candidate-order invariance: {'PASS' if order_result['passed'] else 'FAIL'} (max|diff|={order_result['max_abs_diff']:.2e})")

mask_result = mode_b_audit.spectrum_mask_control(model0, val0, model_features=MODEL_FEATURES, sample_n=200, seed=SEED)
print(f"spectrum-mask sensitivity: {'PASS' if mask_result['sensitive'] else 'FAIL'} "
      f"(n_sampled={mask_result['n_sampled']}, mean|shift|={mask_result['mean_abs_shift']:.4f})")

checks.append(CheckResult("candidate-order control (Mode-B model)", order_result["passed"], f"max|diff|={order_result['max_abs_diff']:.2e}"))
checks.append(CheckResult("spectrum-mask control (Mode-B model)", mask_result["sensitive"], f"mean|shift|={mask_result['mean_abs_shift']:.4f}"))

candidate-order invariance: PASS (max|diff|=0.00e+00)
spectrum-mask sensitivity: PASS (n_sampled=200, mean|shift|=11.1932)

## 7. Verdict

Section 1.7/1.8's decision rule: is `mode_b_unseen_connectivity_mrr25 ~= 0.4999` trustworthy as a Class-2 (unseen-structure) result? Computed from the live numbers above, not hand-typed.

In [9]:
SHORTCUT_MRR_RECOVERY_THRESHOLD = 0.60  # missingness-only recovering >=60% of the full model's MRR is decisive
CONSTANT_COLLAPSE_TOLERANCE = 0.03       # constant-control within 0.03 MRR of mass-only == "collapsed to mass-only"

collapses_to_mass_only = abs(constant_control["constant_spectral_features_mrr_at_25"] - mass_only_mrr) <= CONSTANT_COLLAPSE_TOLERANCE
missingness_only_dominates = fraction_of_full_model_recovered >= SHORTCUT_MRR_RECOVERY_THRESHOLD
perfect_true_separation = missingness_summary["p_all_nan_given_true"] == 1.0

shortcut_confirmed = perfect_true_separation and (collapses_to_mass_only or missingness_only_dominates)

print("=" * 70)
print("MODE-B SHORTCUT AUDIT -- VERDICT")
print("=" * 70)
print(f"P(all spectral NaN | true candidate)         = {missingness_summary['p_all_nan_given_true']:.4f}  (1.0 = perfect separator by construction)")
print(f"P(all spectral NaN | false candidate)        = {missingness_summary['p_all_nan_given_false']:.4f}  (~= 1/n_folds would confirm fold-membership leakage)")
print(f"median per-query all-NaN fraction            = {missingness_summary['per_query_all_nan_fraction_median']:.4f}  (expected 1/n_folds = {missingness_summary['expected_fold_fraction']:.4f})")
print(f"fold-membership shortcut flag (section 1.3)  = {missingness_summary['fold_membership_shortcut_flag']}")
print(f"mass-only WITHIN all-NaN subset MRR@25       = {missing_subset_mass_only['end_to_end']['mrr_at_25']:.4f}  ({fraction_explained_by_missing_subset_mass_only:.1%} of full Mode-B MRR)")
print(f"real-feature Mode-B MRR@25                   = {constant_control['real_features_mrr_at_25']:.4f}")
print(f"constant-spectral-feature-control MRR@25     = {constant_control['constant_spectral_features_mrr_at_25']:.4f}  (collapses to ~mass-only: {collapses_to_mass_only})")
print(f"missingness-only diagnostic model MRR@25     = {missingness_only_result['mrr_at_25']:.4f}  ({fraction_of_full_model_recovered:.1%} of full Mode-B MRR; dominates: {missingness_only_dominates})")
print()
if shortcut_confirmed:
    print("VERDICT: SHORTCUT CONFIRMED.")
    print("Mode-B's 0.4999 MRR@25 is INVALID as a Class-2/unseen-structure result. It is driven by")
    print("the missingness pattern of spectral features acting as a fold-membership fingerprint --")
    print("NOT by the model learning to generalize spectral evidence to structures without their")
    print("own reference spectra. Per section 1.8, this cannot be fixed by hiding only the true")
    print("structure's spectra (that would make 'truth = only candidate without direct spectra' an")
    print("even STRONGER shortcut) -- a trustworthy Mode B requires external database decoys that")
    print("also lack reference spectra (notebook 06), so missingness stops uniquely identifying the")
    print("true candidate.")
else:
    print("VERDICT: SHORTCUT NOT CONFIRMED by these controls (re-examine thresholds/assumptions above).")
print("=" * 70)

mode_b_status = "INVALID_FOLD_MISSINGNESS_SHORTCUT" if shortcut_confirmed else "UNRESOLVED"
checks.append(CheckResult("Mode-B verdict computed from live audit numbers", True, f"status={mode_b_status}"))

======================================================================
MODE-B SHORTCUT AUDIT -- VERDICT
======================================================================
P(all spectral NaN | true candidate)         = 1.0000  (1.0 = perfect separator by construction)
P(all spectral NaN | false candidate)        = 0.1987  (~= 1/n_folds would confirm fold-membership leakage)
median per-query all-NaN fraction            = 0.2076  (expected 1/n_folds = 0.2000)
fold-membership shortcut flag (section 1.3)  = True
mass-only WITHIN all-NaN subset MRR@25       = 0.5218  (104.4% of full Mode-B MRR)
real-feature Mode-B MRR@25                   = 0.4999
constant-spectral-feature-control MRR@25     = 0.2532  (collapses to ~mass-only: False)
missingness-only diagnostic model MRR@25     = 0.5036  (100.7% of full Mode-B MRR; dominates: True)

VERDICT: SHORTCUT CONFIRMED.
Mode-B's 0.4999 MRR@25 is INVALID as a Class-2/unseen-structure result. It is driven by
the missingness pattern of spectral features acting as a fold-membership fingerprint --
NOT by the model learning to generalize spectral evidence to structures without their
own reference spectra. Per section 1.8, this cannot be fixed by hiding only the true
structure's spectra (that would make 'truth = only candidate without direct spectra' an
even STRONGER shortcut) -- a trustworthy Mode B requires external database decoys that
also lack reference spectra (notebook 06), so missingness stops uniquely identifying the
true candidate.
======================================================================

## 8. Persist audit artifacts

`mode_b_shortcut_audit.parquet` (per-query missingness/verdict detail), a JSON summary, and a new `notebook_09_mode_b_audit` baseline-registry entry that marks the existing `notebook_09_lambdamart` Mode-B number as invalid for downstream selection/reporting -- it is NOT deleted or overwritten (the registry refuses silent overwrites by design), only superseded by this audit entry.

In [10]:
# Section 1.6 schema: EVERY intended query gets a row, including the 4 dev queries with zero
# unseen-connectivity candidates at all (left-joined against the full all_dev_query_ids
# denominator, not just the ones present in unseen_table) -- exactly the "never silently drop a
# query" fix audit.py's own constant/missingness-only functions needed (section 4 above).
per_query_stats = unseen_augmented.groupby("query_id").agg(
    fold=("fold", "first"),
    n_candidates=("candidate_connectivity_key", "count"),
    n_all_spectral_nan=("all_spectral_nan", "sum"),
    fraction_all_spectral_nan=("all_spectral_nan", "mean"),
    true_candidate_present=("is_true_candidate", "any"),
).reset_index()

true_ranks_unseen = true_candidate_rank(lmart_unseen_ranked)  # NOT reindexed yet -- conditional only
missing_subset_ranked = rank_candidates(
    unseen_augmented[unseen_augmented["all_spectral_nan"]].assign(score=-unseen_augmented.loc[unseen_augmented["all_spectral_nan"], "abs_mass_error_ppm"]),
    score_col="score", ascending=False,
)
mass_only_subset_ranks = true_candidate_rank(missing_subset_ranked)

per_query_audit = pd.DataFrame({"query_id": all_dev_query_ids}).merge(per_query_stats, on="query_id", how="left")
per_query_audit["n_candidates"] = per_query_audit["n_candidates"].fillna(0).astype(int)
per_query_audit["n_all_spectral_nan"] = per_query_audit["n_all_spectral_nan"].fillna(0).astype(int)
per_query_audit["true_candidate_present"] = per_query_audit["true_candidate_present"].fillna(False)
per_query_audit["true_candidate_all_nan"] = per_query_audit["true_candidate_present"]  # by construction (P(all_nan|true)=1.0, verified in section 2)
per_query_audit["true_candidate_rank_mode_b"] = per_query_audit["query_id"].map(true_ranks_unseen)
per_query_audit["mass_only_rank_inside_nan_subset"] = per_query_audit["query_id"].map(mass_only_subset_ranks)
per_query_audit["mode_b_reciprocal_rank"] = per_query_reciprocal_rank(per_query_audit.set_index("query_id")["true_candidate_rank_mode_b"].reindex(all_dev_query_ids), k=25)
per_query_audit["reciprocal_rank_inside_nan_subset"] = per_query_reciprocal_rank(per_query_audit.set_index("query_id")["mass_only_rank_inside_nan_subset"].reindex(all_dev_query_ids), k=25)

assert len(per_query_audit) == len(all_dev_query_ids), "every intended query must have exactly one row -- section 1.6's fix"
n_zero_candidate_queries = int((per_query_audit["n_candidates"] == 0).sum())
print(f"{n_zero_candidate_queries} / {len(all_dev_query_ids)} dev queries have ZERO unseen-connectivity candidates at all -- "
      f"present in this table with n_candidates=0, RR=0 (not dropped)")

audit_path = AUDIT_PROCESSED / "mode_b_shortcut_audit.parquet"
per_query_audit.to_parquet(audit_path, index=False)
print(f"saved {len(per_query_audit):,} rows to {audit_path}")

audit_summary = {
    "missingness_summary": missingness_summary,
    "missing_subset_mass_only_mrr25": missing_subset_mass_only["end_to_end"]["mrr_at_25"],
    "fraction_explained_by_missing_subset_mass_only": fraction_explained_by_missing_subset_mass_only,
    "constant_control": {k: v for k, v in constant_control.items() if k not in ("real_metrics", "constant_metrics")},
    "mass_only_mrr25": mass_only_mrr,
    "constant_collapses_to_mass_only": collapses_to_mass_only,
    "missingness_only_mrr25": missingness_only_result["mrr_at_25"],
    "fraction_of_full_model_recovered_by_missingness_only": fraction_of_full_model_recovered,
    "missingness_only_dominates": missingness_only_dominates,
    "candidate_order_control_passed": order_result["passed"],
    "spectrum_mask_control_sensitive": mask_result["sensitive"],
    "shortcut_confirmed": shortcut_confirmed,
    "mode_b_status": mode_b_status,
    "reproduced_mode_a_mrr25": reproduced["mode_a_known_spectrum_mrr25"],
    "reproduced_mode_b_mrr25": reproduced["mode_b_unseen_connectivity_mrr25"],
}
summary_path = REPORTS_DIR / "mode_b_shortcut_audit_summary.json"
with open(summary_path, "w", encoding="utf-8") as f:
    json.dump(audit_summary, f, indent=2, default=str)
print(f"saved audit summary to {summary_path}")

register_baseline("notebook_09_mode_b_audit", {
    "audited_baseline": "notebook_09_lambdamart",
    "audited_mode_b_mrr25": mode_b_mrr25_registered,
    "status": mode_b_status,
    "shortcut_confirmed": shortcut_confirmed,
    "p_all_nan_given_true": missingness_summary["p_all_nan_given_true"],
    "p_all_nan_given_false": missingness_summary["p_all_nan_given_false"],
    "constant_control_mrr25": constant_control["constant_spectral_features_mrr_at_25"],
    "missingness_only_mrr25": missingness_only_result["mrr_at_25"],
    "mass_only_mrr25": mass_only_mrr,
# overwrite=True: unlike a one-time historical baseline, this audit is expected to be re-run as
# the pipeline evolves, and LightGBM's fold-model training has minor cross-run float
# nondeterminism (fixed random_state, but multi-threaded histogram building) even though the
# qualitative verdict (SHORTCUT CONFIRMED, same ballpark MRR) is stable across runs.
}, BASELINE_REGISTRY_PATH, source_notebook="09b_mode_b_shortcut_audit.ipynb", overwrite=True)

# Part 0's requested standing location for baseline history -- a full copy of the registry,
# refreshed every time this notebook runs.
with open(BASELINE_REGISTRY_PATH, encoding="utf-8") as f:
    full_registry = json.load(f)
reports_registry_path = REPORTS_DIR / "baseline_registry.json"
with open(reports_registry_path, "w", encoding="utf-8") as f:
    json.dump(full_registry, f, indent=2, default=str)
print(f"copied full registry ({len(full_registry)} entries) to {reports_registry_path}")

checks.append(CheckResult("audit artifacts persisted", audit_path.exists() and summary_path.exists(), str(AUDIT_PROCESSED)))
checks.append(CheckResult("baseline registry updated with audit verdict, historical entry untouched",
                           "notebook_09_mode_b_audit" in list_baselines(BASELINE_REGISTRY_PATH), ""))

4 / 1000 dev queries have ZERO unseen-connectivity candidates at all -- present in this table with n_candidates=0, RR=0 (not dropped)

saved 1,000 rows to C:\Users\myben\OneDrive\Documents\Enveda\data\processed\mode_b_audit\mode_b_shortcut_audit.parquet
saved audit summary to C:\Users\myben\OneDrive\Documents\Enveda\outputs\reports\mode_b_shortcut_audit_summary.json
copied full registry (3 entries) to C:\Users\myben\OneDrive\Documents\Enveda\outputs\reports\baseline_registry.json

## 9. Final validation checklist

In [11]:
all_passed, checks_dict = summarize_checks(checks)
checklist_df = pd.DataFrame([{"Check": name, "Status": "PASS" if ok else "FAIL"} for name, ok in checks_dict.items()])
display(checklist_df)
print(f"\n{'ALL CHECKS PASS' if all_passed else 'SOME CHECKS FAILED -- see table above'}")

TOTAL_RUNTIME_S = time.time() - NOTEBOOK_START_TIME
print(f"\nRuntime: {TOTAL_RUNTIME_S:.1f}s")
print(f"\nMode-B status: {mode_b_status}")
print("Per section 1.7: this status must be used for model selection / feature selection / progress")
print("claims / leaderboard projections until a genuine external-decoy Mode B (notebook 06) exists.")

                                                Check Status
0                           upstream artifacts loaded   PASS
1   reproduced fold models match notebook 09's reg...   PASS
2   missingness table computed on real Mode-B pair...   PASS
3        mass-only-within-all-NaN-subset MRR computed   PASS
4          constant-spectral-feature control computed   PASS
5   missingness-only diagnostic model trained and ...   PASS
6              candidate-order control (Mode-B model)   PASS
7                spectrum-mask control (Mode-B model)   PASS
8     Mode-B verdict computed from live audit numbers   PASS
9                           audit artifacts persisted   PASS
10  baseline registry updated with audit verdict, ...   PASS

ALL CHECKS PASS

Runtime: 49.0s

Mode-B status: INVALID_FOLD_MISSINGNESS_SHORTCUT
Per section 1.7: this status must be used for model selection / feature selection / progress
claims / leaderboard projections until a genuine external-decoy Mode B (notebook 06) exists.